name: Dependabot Auto merge

on:
  pull_request_target
    
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
